language: swift
xcode_workspace: Example/RSFontSizes.xcworkspace
xcode_scheme: RSFontSizes-Example
osx_image: xcode10.3
xcode_sdk: iphonesimulator12.4
install: true
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.cocoapods/
podfile: Example/Podfile
before_install:
- gem install cocoapods-acknowledgements
- gem install cocoapods
- pod update --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/RSFontSizes.xcworkspace -scheme RSFontSizes-Example -sdk iphonesimulator12.4 -destination 'platform=iOS Simulator,name=iPhone XS Max,OS=12.4' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
